package com.omar.smartshop.data.model

/**
 * Represents a product in the shop. This is the primary data class used throughout the app.
 *
 * @property id Unique identifier for the product, typically generated by Firestore.
 * @property name The name of the product.
 * @property price The selling price of the product.
 * @property quantity The current stock quantity of the product.
 */
data class Product(
    val id: String = "",
    val name: String = "",
    val price: Double = 0.0,
    val quantity: Int = 0
)
